declare -x TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n0000jgm0004bx/T/
declare -x __CF_USER_TEXT_ENCODING=0x117D:0x0:0x1
declare -x HOME=/Users/muteza
declare -x SHELL=/bin/zsh
declare -x Apple_PubSub_Socket_Render=/private/tmp/com.apple.launchd.SLDKGW2TeJ/Render
declare -x SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.3nNtmyzRyT/Listeners
declare -x PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/usr/local/munki:~/.dotnet/tools
declare -x LOGNAME=muteza
declare -x XPC_SERVICE_NAME=0
declare -x MallocNanoZone=0
declare -x USER=muteza
declare -x XPC_FLAGS=0x0
declare -x ORIGINAL_XDG_CURRENT_DESKTOP=undefined
declare -x TERM_PROGRAM=vscode
declare -x TERM_PROGRAM_VERSION=1.73.0
declare -x LANG=en_US.UTF-8
declare -x COLORTERM=truecolor
declare -x GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
declare -x VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper.app/Contents/MacOS/Code Helper
declare -x VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
declare -x VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
declare -x VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n0000jgm0004bx/T/vscode-git-b620f69b66.sock
declare -x VSCODE_INJECTION=1
declare -x ZDOTDIR=/Users/muteza
declare -x USER_ZDOTDIR=/Users/muteza
declare -x PWD=/Users/muteza/Desktop/Minishell
declare -x TERM=xterm-256color
declare -x SHLVL=1
declare -x OLDPWD=/Users/muteza/Desktop
declare -x ZSH=/Users/muteza/.oh-my-zsh
declare -x PAGER=less
declare -x LESS=-R
declare -x LSCOLORS=Gxfxcxdxbxegedabagacad
declare -x _=/Users/muteza/Desktop/Minishell/./Minishell
